/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: Orquestación de Pedidos Event-Driven en NestJS y Renderizado Next.js
   Architecture: Monolith Architecture (MVC / Monolithic)
   Stack: typescript + nestjs + prisma
   Generated by gherkin-ai CLI v3.0.0-beta.1
   ========================================================================== */

import { z } from 'zod';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}

export interface Event1 extends IDomainEvent {
  eventType: 'CanonicalOrderCreated';
  payload: {

  };
}

export interface Event2 extends IDomainEvent {
  eventType: 'NextjsAppRouterDebeRecibirActualizacinMedianteServerSentEvenEvent';
  payload: {

  };
}

// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsCommandSchema = z.object({
  requestId: z.string().uuid(),
  timestamp: z.string().datetime(),
  payload: z.object({

  })
});

export type OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsCommand = z.infer<typeof OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsCommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface IOrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsRepository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}
