/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Orquestación de Pedidos Event-Driven en NestJS y Renderizado Next.js
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsFixture {
  id: string;

}

export function createOrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsFixture(): OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsFixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',

  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "que se envía un Payload JSON de Shopify a NestJS"
];
