// Domain kernel for "Orquestación de Pedidos Event-Driven en NestJS y Renderizado Next.js" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.

export type OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsState = 'PENDING';
export type OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsEventType = 'CanonicalOrderCreated' | 'NextjsAppRouterDebeRecibirActualizacinMedianteServerSentEven' | 'OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsProcessed';

export interface OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsDomainEvent {
  type: OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsEventType;
  aggregateId: string;
  version: number;
  occurredOn: Date;
  payload: Record<string, unknown>;
}

export interface OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsCommand {
  /** Identifier of the aggregate the command targets. */
  id: string;
  payload?: Record<string, unknown>;
}

export class DomainValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'DomainValidationError';
  }
}

export class OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsAggregate {
  private _state: OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsState = 'PENDING';
  private _version = 0;
  private readonly _events: OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsDomainEvent[] = [];

  constructor(public readonly id: string) {
    if (!id || !id.trim()) throw new DomainValidationError('OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJs id is required');
  }

  /** Rebuilds an aggregate from persisted state; no events are recorded. */
  static restore(id: string, state: OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsState, version: number): OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsAggregate {
    const aggregate = new OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsAggregate(id);
    aggregate._state = state;
    aggregate._version = version;
    return aggregate;
  }

  get state(): OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsState {
    return this._state;
  }

  get version(): number {
    return this._version;
  }

  /** Events recorded since the aggregate was loaded (to be saved via an outbox). */
  get pendingEvents(): readonly OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsDomainEvent[] {
    return this._events;
  }

  processOrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJs(command: OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsCommand): OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsDomainEvent {
    this.assertValid(command);
    return this.record('CanonicalOrderCreated', command.payload ?? {});
  }

  private assertValid(command: OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsCommand): void {
    if (!command || !command.id || !command.id.trim()) throw new DomainValidationError('Command id is required');
    if (command.id !== this.id) throw new DomainValidationError(`Command targets ${command.id}, not ${this.id}`);
  }

  private record(type: OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsEventType, payload: Record<string, unknown>): OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsDomainEvent {
    this._version += 1;
    const event: OrquestacionDePedidosEventDrivenEnNestJsYRenderizadoNextJsDomainEvent = { type, aggregateId: this.id, version: this._version, occurredOn: new Date(), payload };
    this._events.push(event);
    return event;
  }
}
